"""Mapping issue with product and category solved

Revision ID: f30c5d2538c3
Revises: ef476cfc45f6
Create Date: 2026-03-08 20:20:04.513626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30c5d2538c3'
down_revision: Union[str, Sequence[str], None] = 'ef476cfc45f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('categoryId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['category.uid'], name=op.f('product_categoryId_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('product_pkey'))
    )
    # ### end Alembic commands ###
